apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.18.12
appVersion: 2.0.0-100-g45e7661
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.6.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
- name: mariadb
  version: 20.2.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.29.0
