apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.15.1
appVersion: 2.0.0-95-g5cad5af
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 19.0.3
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
