apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.15.2
appVersion: 2.0.0-95-g5cad5af
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.4.11
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
- name: mariadb
  version: 19.0.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.20.5
