apiVersion: v2
name: langstroth
description: A Helm chart for Kubernetes
type: application
version: 0.2.2
appVersion: '3515443'
dependencies:
- name: memcached
  version: 6.2.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 11.3.1
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
