apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.2.1
appVersion: 2.0.0-83-g7d10f38
dependencies:
- name: memcached
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 11.3.1
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
