apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.19.6
appVersion: 2.0.0-105-g6ace569
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.8.6
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
- name: mariadb
  version: 21.0.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.3
