apiVersion: v2
name: langstroth
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: 34718ce
dependencies:
- name: memcached
  version: 5.15.8
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 9.8.1
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
