apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.9.0
appVersion: 2.0.0-84-g4e4a255
sources:
  - https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 18.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
