apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.19.9
appVersion: 2.0.0-108-g6d9cd4d
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.9.4
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
- name: mariadb
  version: 21.0.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.3
