apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.18.2
appVersion: 2.0.0-97-gb67ad2d
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.4.15
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
- name: mariadb
  version: 19.0.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.22.0
