apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.11.1
appVersion: 2.0.0-90-g3f8b5e5
sources:
- https://github.com/NeCTAR-RC/langstroth-helm.git
dependencies:
- name: memcached
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 18.2.3
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
