apiVersion: v2
name: langstroth
description: A Helm chart for a Nectar status site (Langstroth)
type: application
version: 1.1.18
appVersion: 2.0.0-43-g52706c2
dependencies:
- name: memcached
  version: 6.2.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.memcached
- name: mariadb
  version: 11.3.1
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
