apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langstroth.fullname" . }}
  labels:
    {{- include "langstroth.labels" . | nindent 4 }}
data:
  settings.py: |
{{ include "local_settings" . | indent 4 }}
