apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langstroth.fullname" . }}
  labels:
    {{- include "langstroth.labels" . | nindent 4 }}
data:
  settings.py: |
{{ include "local_settings" . | indent 4 }}
  apache.conf: |
    Listen 0.0.0.0:80

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog /dev/stdout combined env=!forwarded
    CustomLog /dev/stdout proxy env=forwarded

    <VirtualHost *:80>
      WSGIDaemonProcess horizon processes=1 threads=5 user=horizon group=horizon display-name=%{GROUP}
      WSGIProcessGroup horizon
      WSGIScriptAlias / /var/lib/horizon/wsgi.py
      WSGIApplicationGroup %{GLOBAL}
      LimitRequestBody 2147483647
      ErrorLogFormat "%{cu}t %M"
      ErrorLog /dev/stdout
  
      <Directory /var/lib/horizon>
        Require all granted
      </Directory>

      SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
      CustomLog /dev/stdout combined env=!forwarded
      CustomLog /dev/stdout proxy env=forwarded
      
      Alias /static /var/lib/kolla/venv/lib/python3.8/site-packages/static
       <Directory /var/lib/kolla/venv/lib/python3.8/site-packages/static>
        Require all granted
      </Directory>
    </VirtualHost>
